
SET(BUILD_NUMBER "999")

IF(DEFINED ENV{TRAVIS_BUILD_NUMBER})
    SET(BUILD_NUMBER $ENV{TRAVIS_BUILD_NUMBER})
ENDIF()

file (STRINGS "${CMAKE_SOURCE_DIR}/.version" PROJECT_VERSION)


configure_file(
    ${CMAKE_SOURCE_DIR}/src/version.h.in 
    ${CMAKE_SOURCE_DIR}/src/version.h
)

set(PROJECT_VERSION_MAJOR)
set(CPACK_PACKAGE_VERSION_MINOR "${PROJECT_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PROJECT_VERSION_PATCH}")



